# Generated by Django 5.0.1 on 2024-03-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='massage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage_image', to='posts.massage'),
        ),
    ]
