# Generated by Django 5.0.1 on 2024-03-03 08:06

from django.db import migrations


def first_user(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model("auth", "User")
    User.objects.create(username="Alex", first_name="Alex", last_name="Sean", email="alex@mail.com",
                        password="Alex12345_")


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(first_user),
    ]
